"""Initial migration

Revision ID: 7a79c10de8a5
Revises: 
Create Date: 2025-08-07 20:53:17.788938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a79c10de8a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('serial_number', sa.String(length=120), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_serial_number'), ['serial_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('laptop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('serial_number', sa.String(length=120), nullable=True),
    sa.Column('is_stolen', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ibeacon_uuid', sa.String(length=36), nullable=True),
    sa.Column('ibeacon_major', sa.Integer(), nullable=True),
    sa.Column('ibeacon_minor', sa.Integer(), nullable=True),
    sa.Column('ibeacon_mac_address', sa.String(length=17), nullable=True),
    sa.Column('ultrasonic_sensor_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('laptop', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_laptop_ibeacon_mac_address'), ['ibeacon_mac_address'], unique=True)
        batch_op.create_index(batch_op.f('ix_laptop_serial_number'), ['serial_number'], unique=True)

    op.create_table('sensor_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ibeacon_uuid', sa.String(length=36), nullable=True),
    sa.Column('ibeacon_major', sa.Integer(), nullable=True),
    sa.Column('ibeacon_minor', sa.Integer(), nullable=True),
    sa.Column('ibeacon_mac_address', sa.String(length=17), nullable=True),
    sa.Column('ibeacon_rssi', sa.Integer(), nullable=True),
    sa.Column('ultrasonic_distance_1_cm', sa.Float(), nullable=True),
    sa.Column('ultrasonic_distance_2_cm', sa.Float(), nullable=True),
    sa.Column('ultrasonic_distance_3_cm', sa.Float(), nullable=True),
    sa.Column('ultrasonic_distance_4_cm', sa.Float(), nullable=True),
    sa.Column('ultrasonic_intrusion_detected', sa.Boolean(), nullable=True),
    sa.Column('laptop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['laptop_id'], ['laptop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensor_reading', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensor_reading_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_reading', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensor_reading_timestamp'))

    op.drop_table('sensor_reading')
    with op.batch_alter_table('laptop', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_laptop_serial_number'))
        batch_op.drop_index(batch_op.f('ix_laptop_ibeacon_mac_address'))

    op.drop_table('laptop')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_log_serial_number'))

    op.drop_table('log')
    # ### end Alembic commands ###
